### ISSUE TITLE
Can't run it on a chromebook

### ISSUE THREAD

**Issue by TrinTrin2002** [gamejolt/next-issue-tracker#1140]
Really hope you get a chromebook version for the editor... you can't run it on a chromebook currently

**Comment by Tricky1975** [comment]
Editor? What exactly do you mean?
Please there ins't a chromebook version of anything, since all a chromebook is, is a browser disguised as an OS. Nothing you cannot run outside a browser can run on a chromebook and anything that works in Google Chrome browser on Mac, Linux or Windows should work on a chromebook, as long as it's taken from a distant website. 

Google's philosophy behind ChromeOS was that all you need is a webbrowser and nothing more, and that's exactly what a Chromebook (which runs ChromeOS) provides and nothing more. Therefore I deem it highly possible you are trying to do stuff a Chromebook was never intended to be able to, and that what you are facing is thus not a GJ issue, and if it is, you'll have to be more detailed and more specific about what you are referring to.

**Comment by qwertychouskie** [comment]
Well, they can also run Android apps, though that is only good for a few games like SuperTuxKart that have an Android version.  Better wait for that Linux app support: https://www.blog.google/products/chromebooks/linux-on-chromebooks/
