### ISSUE TITLE
Lots of distributions take up too much space

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#121]
When I take my "Secrets of Dyrt" project for example, which has quite a lot of different distributions so the ideal game to come up with this, I first see all the distros I can support on my system and under that the game's description. At this game in particular it gave me quite a long way to scroll down I actually saw the game's description. I'm not quite sure my next potential downloaders are charmed by that as I believe they want to read the description first before they decide if my game is worthy a download or not. So maybe it can be a good idea to place a "download" link only above the description and when people click it that all the downloads get shown the way it does now by default. 

Now I admit that Dyrt has extremely much downloadable options, but I'm pretty sure it's not the only one with multiple options.

(I mean this screenshot shows a whole lot of distros for my game, and those aren't even all of them)
![image](https://cloud.githubusercontent.com/assets/11202073/6382731/78055368-bd4b-11e4-9c59-01bd48e1c82b.png)

**Comment by hworld** [comment]
I'd like to get more feedback on this from other users. Not sure if you want to link in the forum maybe? The thing is that not many games have so many distros, so this is somewhat of a unique case. My understanding is that most users just try to find the "download/play" button as quick as possible, especially if you link on Twitter or some social network. They already know they want to play it.

Game descriptions can be pretty long some times. It would push down the immediately visible "Download" button and possibly get some bounces due to not being able to find it right away.

On the flipside many game descriptions have important instructions on how to play. Though for downloads you can easily start a download and scroll down to description to read as it's downloading. And for browser games you can minimize to read description.

Anyway, what are other people's thoughts?

**Comment by Tricky1975** [comment]
I copied this to the forum, as this can indeed be a good issue for discussion. (It was marked for review though).

**Comment by Agrosis** [comment]
In my opinion, it feels as if you don't really need a description at all, really. I don't think games require that much instruction. There should only be that one description, really. After all, you've got a title and a platform, your game should be a simple download or install.

Also, the repeated avatar to the left of each distribution seems a bit too redundant. IMO, I think the old way of distributions was pretty concise, it let people quickly identify what they want without seeing a bunch of fluff and get playing.

**Comment by Tricky1975** [comment]
"Also, the repeated avatar to the left of each distribution seems a bit too redundant."
Yeah, I too think that might indeed be a little bit too much.

**Comment by hworld** [comment]
@Agrosis, I put the reasoning behind thumbnails in the forum topic: http://gamejolt.com/community/forums/topics/lots-of-distros-take-up-too-much-space/6343/

**Comment by hworld** [comment]
FYI that the new releases styling collapses it into a much smaller view. It also allows for a lot more builds showing up in one package. This is the beginning of a completely new build/distribution/package management system that I've been working on.

![screenshot from 2015-04-02 13 35 34](https://cloud.githubusercontent.com/assets/1024321/6994695/1184980e-dae9-11e4-8919-4537dee536da.png)

It's not done, but it's getting there and should help a lot with stuff like this.

**Comment by TrickyRachel** [comment]
Hmm.... that looks good....

**Comment by hworld** [comment]
So, yeah, with the new builds system this is fixed, so I'm closing. It won't be visible until we launch, though. But it's much better and more compact.
