### ISSUE TITLE
Some games won't load

### ISSUE THREAD

**Issue by KarmalSerup** [gamejolt/next-issue-tracker#1254]
I'm trying to play some games i installed with Client, but when I try to load the game, the only things that happen are an error sound appears, a popup shows, or nothing happens at all, just the game crashes before it even starts.
![Screenshot (13)](https://user-images.githubusercontent.com/48449404/54141382-f0f5be80-43fb-11e9-8b92-2c0b2f01e708.png)

**Comment by YLivay** [comment]
That is not any error our client throws, looks like its a message from the actual game. If you download and execute it from the browser does it work then?

The developer might not have set correct launch options for the game, if you link it I could take a look.

**Comment by KarmalSerup** [comment]
Hello!
Thanks for responding to my issue.
I have attempted to open the games through downloading them from the website, but that doesn't seem to work either, along with opening the file through the client.

These are the games that currently don't work for me:
https://gamejolt.com/games/five-nights-at-the-krusty-krab/44973
https://gamejolt.com/games/five-nights-at-the-chum-bucket/61137
https://gamejolt.com/games/FinalNights4/267878

**Comment by YLivay** [comment]
Hey, sorry for the late response.

if the games dont work even when launching them from the website it means there's an issue with the game or your setup. I checked the launch options for these games anyways and they seem to be defined correctly. Troubleshooting individual games is out of my scope however so the best bet is to check for issues on your own computer and reaching out to the developers if you think the issue is on their end.
