### ISSUE TITLE
Profane word in Newly Added section

### ISSUE THREAD

**Issue by Feargeorge** [gamejolt/next-issue-tracker#126]
So, I have been scrolling the new site for problems and other things, and I noticed one thing:

http://prntscr.com/6a2hk8

I do not think there should be profane words on the home page, as children or young people might browse the completed version of GameJolt Next and might see this word. People might also consider this pretty unproffesional too. My suggestion is to remove the word or change it to something more light.

**Comment by hworld** [comment]
Technically you've gotta be 13+ to view the site according to the terms. Also, "shit" appears in many PG movies in the US. I don't consider it to be too harsh a word. And while I consider Game Jolt to be professional, I don't consider it to necessarily be professional in that manner.

I'm curious if others are offended by it. It's really funny to me to read, but if no one else thinks it's funny, maybe it isn't.

**Comment by Tricky1975** [comment]
An American woman once said on TV in my country "What? Can I say F*** on TV here? What a wonderful country this is!"

Well, let's say, I'm not fond of profanity on websites, though the word "shit" does not offend me at all. Maybe because I've been using that word way too much myself. (You all know that English is not my first language and I gotta tell you that "yes", "no" and "shit" were the first English words I learned when I was a kid, so maybe that explains). 

I was actually quite amused by seeing that disclaimer. I love it when somebody does not take himself not TOO seriously. 
I don't see "shit" as a serious case of bad language, as I do think that bad language is a bad thing on a site like this, but we should not exaggerate things, as exaggerating can be a bad thing as well.

But that's my humble opinion.

**Comment by Feargeorge** [comment]
It's just a thought that popped into my mind, I'd not really mind if it's kept, just that there might be people who would take this too seriously.

**Comment by acidpoison** [comment]
I'm not offended, but it seems kind of unnecessary to have curse words. But then again, this is the internet. Home to every swear in the universe, and more.

**Comment by hworld** [comment]
Closing this, though people can add to the discussion if they'd like.
