### ISSUE TITLE
YouTube Video Playback Error  

### ISSUE THREAD

**Issue by ItsEpicBeast** [gamejolt/next-issue-tracker#1286]
**How are you using Game Jolt?**
I am using the client.

**Please describe the issue you are having**

Youtube does not work on the client because of YouTube Video Playback Error.

**Comment by ItsEpicBeast** [comment]
I get that you must be tired of hearing about that but you must fix it on the launcher not just making the players type something on the client.

**Comment by YLivay** [comment]
Can't fix it right now sadly because the codecs required to play some of the videos are non free and client's license is MIT.

Sorry, this is a won't fix for now :(

**Comment by ItsEpicBeast** [comment]
Thx

**Comment by ItsEpicBeast** [comment]
> Can't fix it right now sadly because the codecs required to play some of the videos are non free and client's license is MIT.
> 
> Sorry, this is a won't fix for now :(



Thx

**Comment by Tricky1975** [comment]
Since this is a license issue, rather than a bug, perhaps a kind of message stating that YouTube playback isn't supported (and why) would do well though, as really, if I got a dollar for every time I saw this complaint come by either on chat, or on the forums, or (back when I was a mod) that people even contacted me privately about it, I would be able to buy my own tropical island, build a very large house on it and hire staff who would keep the place clean for the rest of my life. In other words, this is a very common complaint, and since an error appears to pop up due to this issue, it's not that odd people take this for a bug.
