### ISSUE TITLE
Linux client is broken

### ISSUE THREAD

**Issue by Weirdo1312** [gamejolt/next-issue-tracker#1339]
**How are you using Game Jolt?**
Linux Client

**Please describe the issue you are having**
i downloaded the latest version from website but it says it's not updated and it suggests me to download from website but that's what i've done exactly
![image](https://user-images.githubusercontent.com/37030489/68467770-0beb2d80-022c-11ea-928d-e630b5c62088.png)

**Comment by YLivay** [comment]
Woah, thanks for pointing it out. For some reason the installer chooses to download an older version of the client instead of the newest one.

As a temporary fix you can download the client directly from here: https://gamejolt.com/games/gjclient/362412
The client's landing page should've downloaded the latest version as it shows on this page. Very weird!

**Comment by Weirdo1312** [comment]
> Woah, thanks for pointing it out. For some reason the installer chooses to download an older version of the client instead of the newest one.
> 
> As a temporary fix you can download the client directly from here: https://gamejolt.com/games/gjclient/362412
> The client's landing page should've downloaded the latest version as it shows on this page. Very weird!

i opened app in terminal and the update was downloading in the background but the gui won't just show it
in fact the client is fine it just does not show the update progress

**Comment by YLivay** [comment]
Yeah that was a bug in an old version of the client. I also have a fix ready for the wrong version downloading through the client's landing page :)
I'll update when it's pushed.

**Comment by nilllzz** [comment]
No, I'LL update when it's pushed. Which it is. Should be fixed now :)
