### ISSUE TITLE
Safari HTML5 Game Broken

### ISSUE THREAD

**Issue by RodrigoDornelles** [gamejolt/next-issue-tracker#1381]
**How are you using Game Jolt?**

To play html5 games

**Please describe the issue you are having**

my game works correctly in my local tests, but when I use safari on the gamejolt site it is broken
https://rodrigodornelles.gamejolt.io/tedious-game

Gamejolt | Local host
--------- | -----------
![bug](https://cdn.discordapp.com/attachments/693302190328250408/700096248220483594/Captura_de_Tela_2020-04-15_as_18.31.56.png) | ![work](https://cdn.discordapp.com/attachments/693302190328250408/700104326449856522/Captura_de_Tela_2020-04-15_as_19.04.01.png)

**Comment by YLivay** [comment]
This seems to be an issue specifically with how game maker requests resources. Looks like it does anonymous requests so the cookies we set to allow the resources to load aren't being sent over.
I'm looking into this.

Also, WebGL 2.0 is apparently only an experimental feature on Safari that needs to be specifically enabled through the devtools, do you have it enabled on your end? For me the issue persists even after enabling, but that could also be because i'm running it from a VM without a gpu passthrough haha

**Comment by RodrigoDornelles** [comment]
> Also, WebGL 2.0 is apparently only an experimental feature on Safari that needs to be specifically enabled through the devtools, do you have it enabled on your end?

I didn't activate it, but it works locally

**Lite Game:**  the lite version does not have a webgl, but not loads the game sprites

**Comment by YLivay** [comment]
Hey, as I said the issue is with Game Maker, not your game. They specify the asset requests to load using crossOrigin="anonymous" which makes some credentials to not get sent. Problem is, these credentials are what allows you to load the resources from GJ in the first place.

We have a plan on how to bypass this but it might be a bit tricky to implement.
I'll update on this topic as we progress on this.

**Comment by YLivay** [comment]
I know it is incredibly hacky, but as a temporary workaround, you can edit the main js file of your game (it should be called something like your-game.js, you can see it's being used in one of the <script> elements in the index.html GM makes).

In the js file look for something that looks like `var something = "anonymous"` and change the "anonymous" bit to "use-credentials".

**Comment by RodrigoDornelles** [comment]
> I know it is incredibly hacky, but as a temporary workaround, you can edit the main js file of your game (it should be called something like your-game.js, you can see it's being used in one of the <script> elements in the index.html GM makes).
> 
> In the js file look for something that looks like `var something = "anonymous"` and change the "anonymous" bit to "use-credentials".

thanks, that solved it!
