### ISSUE TITLE
Commenting on another page of comments loads back to first page

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/next-issue-tracker#165]
I commented on a comments thread on page 2 of Mond Cards and it refreshed the page back to the first page of comments after submitting the comment.

**Comment by hworld** [comment]
This was a reply to a comment on a second page?

**Comment by acidpoison** [comment]
Yeah. I commented here: http://wttf.gamejolt.com/games/mond-cards/18002?comment_page=2
And it refreshed to here: http://wttf.gamejolt.com/games/mond-cards/18002

**Comment by hworld** [comment]
Yeah, I mean you were replying, right? Because if you are on the second page and add a top-level comment, it should go back to the first page, since your new comment will be first.

Unless you were replying, then your comment will land within the comment thread on the page you're on, and then it shouldn't direct to first page.

**Comment by acidpoison** [comment]
Nope, I was replying to a comment.
![GJ comment bug](http://s15.postimg.org/sx2lj41y3/NEXTbug.png)

**Comment by hworld** [comment]
k, good to know, thanks!

**Comment by hworld** [comment]
Fixed.
