### ISSUE TITLE
Browsing per HTTPS, links to user profiles "silently" switch back to HTTP

### ISSUE THREAD

**Issue by MausGames** [gamejolt/next-issue-tracker#175]
All links on user avatars (bottom left + on game profiles) always use HTTP.

**Comment by hworld** [comment]
Yeah, you can't browse as https because too much content (that I don't have control over) is shown over http. For example, blog posts show insecure content many times, and HTML games call out to insecure URLs some times for ajax, or extra images, or really anything.

I tried really hard to do https-only web site. If you look at the network tab only the first HTML request is http. Everything else behind the scenes is https. All API calls, all asset requests, everything. I just couldn't set the padlock in the URL bar because of the insecure user content.

I can fix user content in news posts/comments by proxying, but that's because I have the ability to rewrite the URLs. With browser games I don't have that ability, so it makes it insecure and throws a warning/error.

I also can't auto-switch when playing games since it's not a new page (it's a modal) and you can minimize and browse site with it still playing.

In the future I may be able to hack service workers into the page to overwrite URLs that get sent out and redirect them through a GJ https proxy. Until then, I'm really not sure what to do.

I'm going to close this, but if you have any ideas, feel free to send them over.

**Comment by MausGames** [comment]
Thank you for the answer, I did not look at the detailed network traffic before.
I will look and test again if I have more time - those two issues I wrote were just quick observations, and I thought they were not intended.

**Comment by MausGames** [comment]
This looks interesting:
https://github.com/atmos/camo

**Comment by hworld** [comment]
Yeah, I've seen that and I will probably implement a proxy to try to get every user-embedded image to be HTTPS, but it still doesn't work for games since we have no control of when they call the non-ssl URL in their javascript.
