### ISSUE TITLE
New news notifications don't link to the article

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/next-issue-tracker#252]
Clicking new news in the notification menu bring you to the game page, not the article itself.

**Comment by hworld** [comment]
I can't seem to replicate this...
I had a news update notification in my notifications dropdown. I hovered over and the link seemed correct. I then when to activity feed instead (something you can't do yet) and checked there as well and that was also fine.
Not sure about this one... Are you sure you didn't get confused since the header still shows the game at the top?

**Comment by acidpoison** [comment]
It's probably just me then. I'll reopen this if it happens again.

**Comment by acidpoison** [comment]
Yeah, I checked it. It works. Maybe I was confused before.
