### ISSUE TITLE
Withdraw amount adjustment buttons are tiny

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/next-issue-tracker#260]
Seriously, they're really small. Even smaller than the old expand description buttons.

I think it would be better to have them stretch to meet the corners of the entry window or even have them put outside the box. It might be a good idea to remove them entirely.

**Comment by hworld** [comment]
Hmmm, that's a browser thing. In the HTML you say it's an input type of "number" and it adds those. I can't do too much about it. Each OS/browser renders them differently and I believe on phones it switches the input to just show numbers, which is beneficial.

Gonna close since it's not so much in my control.
