### ISSUE TITLE
Messy Presentation on lower resolution

### ISSUE THREAD

**Issue by PianoHands** [gamejolt/next-issue-tracker#275]
Would love the ability to minimize chat and the site navigation windows.

**Comment by YLivay** [comment]
Isnt it already the case? On smaller screens stuff goes away. What browser
are you using?
בתאריך 6 ביוני 2015 00:03,‏ "PianoHands" <notifications@github.com> כתב:

**Comment by PianoHands** [comment]
Firefox - 1280 x 1024 && 1360 x 768 resolutions

**Comment by PianoHands** [comment]
Fernando relatively solved it. Pushing the 'x' button clears the clutter. Here's a screenshot of how messy and ugly it looks anyways on my monitor. https://www.dropbox.com/s/4fzi4wy39zw5atb/Screenshot%202015-06-05%2014.13.09.png?dl=0

**Comment by hworld** [comment]
Just for anyone else, you can press `m` to toggle the left menu, or `c` to toggle the right. Pressing `x` will go full screen and toggle both away. You can also press the buttons in the top-left and top-right corners to toggle the side panes.

I show them by default just so that new people to the site can see what is available for them.
