### ISSUE TITLE
Buttons look like they're pressed when they're not [mobile]

### ISSUE THREAD

**Issue by NickRock** [gamejolt/next-issue-tracker#280]
![screenshot_2015-06-04-17-06-54](https://cloud.githubusercontent.com/assets/11754980/8019347/84c20dd4-0c52-11e5-9cbf-6e0ff08f8d32.png)

**Comment by hworld** [comment]
Yeah, it sucks big time. I haven't found a good solution for it yet. It's basically the browsers fault. They trigger "hover" events on elements when you click them and then don't "unhover" them. I would have to add in the styling to try to not do the hover behavior for small screens, but the issue is really touch vs mouse, not necessarily "small screen." The browser doesn't give a good way to say, "only show the hover styling if it's a mouse moving on the element, not if it's a finger pressing it." Until then, I guess we'll have to live with this. -_-
